### ISSUE TITLE
ATTR_EFFECT causing errors since ha 2023.11.1

### ISSUE THREAD

**Issue by TNTLarsn** [pnbruckner/homeassistant-config#162] opened 2023-11-02 19:03 UTC
https://github.com/pnbruckner/homeassistant-config/blob/aa04afe8e32777414abb5a9265c00a90efa5d67c/python_scripts/light_store.py#L20

```
Logger: homeassistant.components.python_script.light_store.py
Source: components/python_script/__init__.py:224
Integration: Python Scripts (documentation, issues)
First occurred: 14:33:51 (1 occurrences)
Last logged: 14:33:51

Error executing script: string value is None for dictionary value @ data['effect']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "light_store.py", line 116, in <module>
  File "/usr/src/homeassistant/homeassistant/core.py", line 1940, in call
    ).result()
      ^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/core.py", line 2001, in async_call
    processed_data: dict[str, Any] = handler.schema(service_data)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
        ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['effect']
```

The Hue-Light I`m using has no "effect", but this had no effect on the script since the recent Homeassistant update

```yaml
min_color_temp_kelvin: 2202
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 454
supported_color_modes:
  - color_temp
color_mode: color_temp
brightness: 74
color_temp_kelvin: 2439
color_temp: 410
hs_color:
  - 29.04
  - 74.777
rgb_color:
  - 255
  - 156
  - 64
xy_color:
  - 0.554
  - 0.389
off_with_transition: false
off_brightness: null
friendly_name: Hängelampe
supported_features: 40
icon: phu:ceiling-fair-semiflush
```

**Comment by pnbruckner** [comment] 2023-11-02 20:06
Please provide more detail. What errors? Under what conditions?

**Comment by TNTLarsn** [comment] 2023-11-03 13:37
> Please provide more detail. What errors? Under what conditions?

Sorry, I was in a hurry yesterday. Just updated the issue

**Comment by pnbruckner** [comment] 2023-11-03 14:34
Thanks.

So, it shouldn't be trying to restore the `effect` attribute if the light did not have that attribute when the state was saved.

Can you share snippets of how you're using this script?

**Comment by TNTLarsn** [comment] 2023-11-03 14:45
```yaml
alias: Turn on scene `Guten Abend` but restore some lights in the kitchen if they are already on
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.abend
    to: "on"
condition: []
action:
  - variables:
      lights:
        - light.led_am_fussboden
        - light.hangelampe
        - light.kuchenspots
  - if:
      - condition: template
        value_template: >-
          {{ states | selectattr('entity_id', 'in', lights ) |
          selectattr('state', 'eq', 'on') | list | count > 0 }}
        alias: Observed lights are on
    then:
      - alias: Save states of observed lights
        service: python_script.light_store
        data:
          store_name: before_scene
          entity_id: >-
            {{ states.light | selectattr('entity_id', 'in', lights ) |
            selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list
            }}
      - service: scene.turn_on
            target:
              entity_id: scene.guten_abend
            metadata: {}
      - alias: restore observed lights
        service: python_script.light_store
        data:
          store_name: before_scene
          operation: restore
    else:
      - service: scene.turn_on
            target:
              entity_id: scene.guten_abend
            metadata: {}

```

**Comment by pnbruckner** [comment] 2023-11-03 15:15
Thanks!

Could you try running the save operation manually (e.g., from the Services page) with those three lights (when they are on)? After it runs, check the States tab for entities whose ID starts with `before_scene.` There should be `before_scene.light_led_am_fussboden`, `before_scene.light_hangelampe` and `before_scene.light_kuchenspots`. Then share their states, including attributes.

Then, you could try running the restore operation manually, and see if it results in the same error.

Actually, before you do any of that, see if any of those `before_scene.xxx` entities are on the States page. If so, share their states & attributes.

**Comment by pnbruckner** [comment] 2023-11-03 15:19
I'm wondering if somehow the State Machine has old `before_scene.xxx` entries, and they're not getting overwritten when saving, and they're not getting deleted when restoring due to the error. If this is happening, it might help to use the overwrite option when saving. I.e.,
```yaml
      - alias: Save states of observed lights
        service: python_script.light_store
        data:
          store_name: before_scene
          overwrite: true
          entity_id: >-
            {{ states.light | selectattr('entity_id', 'in', lights ) |
            selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list
            }}
```

**Comment by TNTLarsn** [comment] 2023-11-03 15:28
https://www.dropbox.com/s/b5s0eqhkzvcwmus/Bildschirmfoto%202023-11-03%20um%2016.23.05.png?dl=0
https://www.dropbox.com/s/fnmuv0odr8ikhhq/Bildschirmfoto%202023-11-03%20um%2016.23.25.png?dl=0
https://www.dropbox.com/s/y3ktzt27h3er2gg/Bildschirmfoto%202023-11-03%20um%2016.23.36.png?dl=0
https://www.dropbox.com/s/yuo8avpq8feq58f/Bildschirmfoto%202023-11-03%20um%2016.23.46.png?dl=0

**Comment by TNTLarsn** [comment] 2023-11-03 17:15
I did it the steps manually an reproduced the error:

1. Called the service to store 3 lights (including the one without effects)
2. Changed brightness of one of the three lights
3. Called the service with `operation: restore`

The error occurs on step 3 no matter of having `overwrite: true` or not

**Comment by pnbruckner** [comment] 2023-11-03 17:36
Thanks. I'd really like to see the state/attributes of those temporary entities in the State Machine that the light_store script creates after the save operation (i.e., step 1 in your test procedure.) Can you please share that information? Of course, this would need to be done without the modification you just made. Without this information I can't understand what is causing the error, and hence, how to fix it.

**Comment by TNTLarsn** [comment] 2023-11-03 17:43
> Thanks. I'd really like to see the state/attributes of those temporary entities in the State Machine that the light_store script creates after the save operation (i.e., step 1 in your test procedure.) Can you please share that information? Of course, this would need to be done without the modification you just made. Without this information I can't understand what is causing the error, and hence, how to fix it.

![My Remote Image](https://www.dropbox.com/s/fnmuv0odr8ikhhq/Bildschirmfoto%202023-11-03%20um%2016.23.25.png?raw=1)
![My Remote Image](https://www.dropbox.com/s/y3ktzt27h3er2gg/Bildschirmfoto%202023-11-03%20um%2016.23.36.png?raw=1)
![My Remote Image](https://www.dropbox.com/s/yuo8avpq8feq58f/Bildschirmfoto%202023-11-03%20um%2016.23.46.png?raw=1)

**Comment by pnbruckner** [comment] 2023-11-03 18:02
So, `light.led_am_fussboden` definitely has an `effect` attribute, and its (Python) value is `None` (which is shown in YAML as `null`.)

I'll check the core code, but my guess in previous versions the `effect` attribute was not present, whereas now it _is_ present, but with a value of `None`.)

If that is the case, then that explains the problem. When the script tries to restore this light entity, it tries to set the `effect` attribute to `None`, which is illegal (in the `light.turn_on` service call.)

If I can confirm all this, I think the fix is to NOT include attributes whose values are `None`.

I'll let you know what I find and if I come up with a working fix.

**Comment by pnbruckner** [comment] 2023-11-03 18:25
Ok, there was a related change in 2023.11:

https://github.com/home-assistant/core/pull/101946

But still, even with that, I don't quite understand how this is happening. The `effect` attribute should only be added to the light's state if the `supported_features` attribute indicates that it should. I.e., only if the light supports effects. But, given that `supported_features` for the light in question is 40, that indicates that effects are NOT supported. (40 indicates only flash and transition features.) So, I don't see how the light_store script is thinking the state of that light has an `effect` attribute.

I tried running the script on my system (I actually don't use it normally) and did not get any errors, but I'm still running HA 2023.10. I'll try upgrading to 2023.11 and see what happens.

This is strange.

**Comment by TNTLarsn** [comment] 2023-11-03 18:34
I was looking on the wrong light beforehand, 
the other light indeed has effects:

```yaml
min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
effect_list:
  - colorloop
supported_color_modes:
  - color_temp
  - xy
color_mode: color_temp
brightness: 16
color_temp_kelvin: 2439
color_temp: 410
hs_color:
  - 29.04
  - 74.777
rgb_color:
  - 255
  - 156
  - 64
xy_color:
  - 0.554
  - 0.389
effect: null
off_with_transition: false
off_brightness: null
friendly_name: LED am Fußboden
supported_features: 44
icon: mdi:led-strip-variant
```

The pull request https://github.com/pnbruckner/homeassistant-config/pull/163 fixed it for me

**Comment by pnbruckner** [comment] 2023-11-03 18:43
Ok. Now it makes more sense.

BTW, that change in 2023.11 not only includes the attributes when the light is off (which it did not do before), but it also includes attributes with None/null values even when the light is on. It used to NOT include any attributes whose values were None/null before. So, this explains the problem.

I'll go ahead and accept your change and make a new release.

**Comment by pnbruckner** [comment] 2023-11-03 19:53
For some reason merging the PR did not close this issue.

**Closed by pnbruckner** 2023-11-03 19:53 UTC
