### ISSUE TITLE
Life360 doesn't show up in Tracker Card

### ISSUE THREAD

**Issue by quantummobile** [pnbruckner/homeassistant-config#101] opened 2019-02-21 19:10 UTC
Hi,

any ideas why life360 does not show up in Tracker Card?

HA 0.88, everything is set up as described here: https://github.com/pnbruckner/homeassistant-config/blob/master/docs/custom_updater.md

![screenshot 2019-02-21 at 21 09 44](https://user-images.githubusercontent.com/47085307/53194850-09549380-361d-11e9-96e3-058e2402a31c.png)

**Comment by pnbruckner** [comment] 2019-02-21 19:27
That's a question for @ludeeus. I'm not sure what I'm supposed to do with the recent changes starting with HA 0.87, and enforced in 0.88.

**Comment by ludeeus** [comment] 2019-02-21 19:39
I _think_ this new structure has been enabled since 0.86.0

Since your cards @pnbruckner are covered by customjson, all users that do not use the `sun` component can just remove the entry from `component_urls`, this is the fast/easy option.

https://github.com/pnbruckner/homeassistant-config/pull/102 will also resolve this.

**Comment by pnbruckner** [comment] 2019-02-22 00:27
This is basically a duplicate of #100.

**Closed by pnbruckner** 2019-02-22 00:27 UTC
Labels: duplicate

**Comment by jonostanck** [comment] 2019-03-01 12:09
Sorry to reopen this but I also can't see life360 in tracker card. I have latest life360 version (2.8.0) installed via custom_updater.install. What am I doing wrong here?

**Comment by SurfingSpider** [comment] 2019-03-01 14:57
Dito. Also Cant see life360.device tracker in the tracker car. I do use the Sun component alot so dont want to disable it?

**Comment by pnbruckner** [comment] 2019-03-01 15:39
@jonostanck @SurfingSpider 

Please make sure you are using the latest & greatest custom_updater.

If you're on HA 0.86 or later, you can either remove the link to the json file on my githhub page from the `component_urls` configuration variable for `custom_updater`, or at least make sure it's pointing to `custom_components.json` (i.e., _not_ `custom_components_old.json`.) But _if you're on a HA version before 0.86_, then you need to use `custom_components_old.json` under `component_urls`.

If none of that solves your problem, then I suggest you ask for help on the [custom_updater issues page](https://github.com/custom-components/custom_updater/issues). I don't use the tracker card so I can't really help with that.

**Comment by jonostanck** [comment] 2019-03-01 15:45
@pnbruckner 

HA 0.88.2, latest & (not so ;P) greatest custom_updater. Tried with and without `custom_components.json` in configuration - guess I have to ask custom_updater authors then...

**Comment by jonostanck** [comment] 2019-03-02 12:30
Well, that's a surprise. Overnight life360 appeared in tracker card and I don't have automated auto-update. That's mysterious but I like it.

**Comment by pnbruckner** [comment] 2019-03-02 13:53
It took a while to get to the bottom of it. See #108.
